"""Declarative base and the column conventions every table follows.

Two rules hold across the whole schema, so they live here rather than being
repeated on each model:

* every table has a ``UUID`` primary key defaulted by PostgreSQL's
  ``gen_random_uuid()`` (the ``pgcrypto`` extension, enabled by the initial
  migration);
* every table has ``created_at`` and ``updated_at`` timestamps in UTC.

The naming convention below makes Alembic emit stable, predictable constraint
names. Without it PostgreSQL invents names for unnamed constraints and
autogenerated migrations become noisy and hard to review.
"""

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import ENUM, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION: dict[str, Any] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds the standard ``id UUID PRIMARY KEY DEFAULT gen_random_uuid()``."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at``, both UTC and set by the database.

    ``updated_at`` is refreshed by SQLAlchemy's ``onupdate`` on ORM flushes. A
    bulk ``UPDATE`` issued as raw SQL will not touch it, so prefer the ORM for
    writes.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def pg_enum(enum_cls: type[StrEnum], name: str) -> ENUM:
    """Build a column type bound to an existing PostgreSQL enum type.

    ``create_type=False`` is deliberate: the initial migration creates every
    enum type up front from ``app.models.enums.ENUM_TYPES``, so the table
    definitions must not try to create them again. It also means
    ``Base.metadata.create_all()`` cannot build this schema — run the Alembic
    migrations instead, which is what the test fixtures do.

    ``values_callable`` stores each member's *value* rather than its Python
    name. They are identical for our ``StrEnum`` members, but being explicit
    keeps the database readable if that ever stops being true.
    """
    return ENUM(
        enum_cls,
        name=name,
        create_type=False,
        values_callable=lambda enum: [member.value for member in enum],
    )
